"""Curated resource library for Velora."""

RESOURCES = [
    # ANXIETY MANAGEMENT
    {"id": "r1", "category": "anxiety", "type": "article", "title": "How to Calm Anxiety: A Field Guide",
     "source": "Headspace", "url": "https://www.headspace.com/anxiety",
     "image": "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600",
     "duration": "8 min read", "description": "Practical techniques for handling anxiety in the moment and over time."},
    {"id": "r2", "category": "anxiety", "type": "video", "title": "The Science of Anxiety — TED-Ed",
     "source": "TED-Ed (YouTube)", "url": "https://www.youtube.com/watch?v=ZidGozDhOjg",
     "image": "https://img.youtube.com/vi/ZidGozDhOjg/maxresdefault.jpg",
     "duration": "5 min", "description": "What's happening in your brain when anxiety strikes — and how to work with it."},
    {"id": "r3", "category": "anxiety", "type": "podcast", "title": "The Anxiety Coaches Podcast",
     "source": "Anxiety Coaches", "url": "https://www.theanxietycoachespodcast.com/",
     "image": "https://images.unsplash.com/photo-1453738773917-9c3eff1db985?w=600",
     "duration": "Series", "description": "Practical episodes on social anxiety, panic, and recovery."},

    # STRESS RELIEF
    {"id": "r4", "category": "stress", "type": "article", "title": "Stress Management Techniques",
     "source": "Mayo Clinic", "url": "https://www.mayoclinic.org/healthy-lifestyle/stress-management",
     "image": "https://images.unsplash.com/photo-1545389336-cf090694435e?w=600",
     "duration": "10 min read", "description": "Evidence-based methods to reduce stress in daily life."},
    {"id": "r5", "category": "stress", "type": "video", "title": "How to Make Stress Your Friend — Kelly McGonigal",
     "source": "TED", "url": "https://www.youtube.com/watch?v=RcGyVTAoXEU",
     "image": "https://img.youtube.com/vi/RcGyVTAoXEU/maxresdefault.jpg",
     "duration": "14 min", "description": "Reframe stress as something useful — a landmark TED talk."},
    {"id": "r6", "category": "stress", "type": "guide", "title": "5-Minute Stress Reset Toolkit",
     "source": "Velora", "url": "https://www.calm.com/blog/stress-relief",
     "image": "https://images.unsplash.com/photo-1500673922987-e212871fec22?w=600",
     "duration": "5 min", "description": "Pocket-sized exercises for instant relief."},

    # MENTAL WELLNESS
    {"id": "r7", "category": "wellness", "type": "article", "title": "What is Mental Wellness?",
     "source": "Global Wellness Institute", "url": "https://globalwellnessinstitute.org/what-is-wellness/what-is-mental-wellness/",
     "image": "https://images.unsplash.com/photo-1499728603263-13726abce5fd?w=600",
     "duration": "6 min read", "description": "The eight dimensions of mental wellness and how to nurture each."},
    {"id": "r8", "category": "wellness", "type": "podcast", "title": "Ten Percent Happier with Dan Harris",
     "source": "Ten Percent Happier", "url": "https://www.tenpercent.com/podcast",
     "image": "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=600",
     "duration": "Series", "description": "Real conversations on meditation, anxiety, sleep, and more."},
    {"id": "r9", "category": "wellness", "type": "video", "title": "All it Takes is 10 Mindful Minutes — Andy Puddicombe",
     "source": "TED", "url": "https://www.youtube.com/watch?v=qzR62JJCMBQ",
     "image": "https://img.youtube.com/vi/qzR62JJCMBQ/maxresdefault.jpg",
     "duration": "9 min", "description": "The Headspace founder on the power of 10 mindful minutes a day."},

    # SELF CONFIDENCE
    {"id": "r10", "category": "confidence", "type": "video", "title": "Your Body Language May Shape Who You Are — Amy Cuddy",
     "source": "TED", "url": "https://www.youtube.com/watch?v=Ks-_Mh1QhMc",
     "image": "https://img.youtube.com/vi/Ks-_Mh1QhMc/maxresdefault.jpg",
     "duration": "21 min", "description": "Power poses, body language, and the science of confidence."},
    {"id": "r11", "category": "confidence", "type": "article", "title": "Building Self-Esteem: A Self-Help Guide",
     "source": "NHS", "url": "https://www.nhs.uk/mental-health/self-help/tips-and-support/raise-low-self-esteem/",
     "image": "https://images.unsplash.com/photo-1517021897933-0e0319cfbc28?w=600",
     "duration": "7 min read", "description": "Practical NHS-backed steps to gently rebuild self-esteem."},
    {"id": "r12", "category": "confidence", "type": "podcast", "title": "Therapy for Black Girls",
     "source": "Dr. Joy Harden Bradford", "url": "https://therapyforblackgirls.com/podcast/",
     "image": "https://images.unsplash.com/photo-1532635241-17e820acc59f?w=600",
     "duration": "Series", "description": "Identity, healing, and confidence — conversations led by a psychologist."},

    # PRODUCTIVITY
    {"id": "r13", "category": "productivity", "type": "article", "title": "The Pomodoro Technique",
     "source": "Todoist", "url": "https://todoist.com/productivity-methods/pomodoro-technique",
     "image": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=600",
     "duration": "4 min read", "description": "25-minute focus sprints that actually work."},
    {"id": "r14", "category": "productivity", "type": "video", "title": "How to Stop Procrastinating",
     "source": "Thomas Frank (YouTube)", "url": "https://www.youtube.com/watch?v=arj7oStGLkU",
     "image": "https://img.youtube.com/vi/arj7oStGLkU/maxresdefault.jpg",
     "duration": "8 min", "description": "Tactical, research-backed steps to stop putting things off."},
    {"id": "r15", "category": "productivity", "type": "podcast", "title": "Deep Questions with Cal Newport",
     "source": "Cal Newport", "url": "https://www.calnewport.com/podcast/",
     "image": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600",
     "duration": "Series", "description": "Deep work, time blocking, and digital minimalism."},

    # FOCUS
    {"id": "r16", "category": "focus", "type": "article", "title": "Train Your Brain for Better Focus",
     "source": "Harvard Business Review", "url": "https://hbr.org/2017/01/how-to-train-your-brain-to-focus",
     "image": "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600",
     "duration": "6 min read", "description": "Neuroscience-based strategies to sharpen attention."},
    {"id": "r17", "category": "focus", "type": "video", "title": "How to Focus to Change Your Brain — Andrew Huberman",
     "source": "Huberman Lab", "url": "https://www.youtube.com/watch?v=LG53Vxum0as",
     "image": "https://img.youtube.com/vi/LG53Vxum0as/maxresdefault.jpg",
     "duration": "1h 51m", "description": "A neuroscientist on protocols for deep, sustained focus."},

    # RELATIONSHIPS
    {"id": "r18", "category": "relationships", "type": "video", "title": "The Lessons of the Longest Study on Happiness — Robert Waldinger",
     "source": "TED", "url": "https://www.youtube.com/watch?v=8KkKuTCFvzI",
     "image": "https://img.youtube.com/vi/8KkKuTCFvzI/maxresdefault.jpg",
     "duration": "13 min", "description": "85 years of Harvard research: relationships are the #1 predictor of happiness."},
    {"id": "r19", "category": "relationships", "type": "article", "title": "How to Communicate Your Feelings",
     "source": "Psychology Today", "url": "https://www.psychologytoday.com/us/blog/communication-success/201408/13-ways-improve-your-communication-skills-in-relationships",
     "image": "https://images.unsplash.com/photo-1529390079861-591de354faf5?w=600",
     "duration": "7 min read", "description": "Honest expression, listening, and conflict skills."},
    {"id": "r20", "category": "relationships", "type": "podcast", "title": "Where Should We Begin? — Esther Perel",
     "source": "Esther Perel", "url": "https://whereshouldwebegin.estherperel.com/",
     "image": "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=600",
     "duration": "Series", "description": "Real anonymous couples therapy sessions, beautifully done."},

    # CAREER GUIDANCE
    {"id": "r21", "category": "career", "type": "article", "title": "How to Find Work You Love",
     "source": "First Round Review", "url": "https://review.firstround.com/how-to-find-work-you-love",
     "image": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600",
     "duration": "12 min read", "description": "Career design from people who've done it."},
    {"id": "r22", "category": "career", "type": "video", "title": "How to Find Work You Love — Scott Dinsmore",
     "source": "TED", "url": "https://www.youtube.com/watch?v=ZS6XAMSlsl0",
     "image": "https://img.youtube.com/vi/ZS6XAMSlsl0/maxresdefault.jpg",
     "duration": "17 min", "description": "Three steps to building a career around what you love."},
    {"id": "r23", "category": "career", "type": "podcast", "title": "The Tim Ferriss Show",
     "source": "Tim Ferriss", "url": "https://tim.blog/podcast/",
     "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600",
     "duration": "Series", "description": "Long-form interviews with world-class performers."},

    # STUDENT WELLNESS
    {"id": "r24", "category": "student", "type": "article", "title": "Student Mental Health: A Survival Kit",
     "source": "Active Minds", "url": "https://www.activeminds.org/blog/category/student-mental-health/",
     "image": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600",
     "duration": "5 min read", "description": "Resources, hotlines, and survival tips for students."},
    {"id": "r25", "category": "student", "type": "video", "title": "How to Beat Test Anxiety",
     "source": "Mind Tools (YouTube)", "url": "https://www.youtube.com/watch?v=FyBH9nLaSPU",
     "image": "https://img.youtube.com/vi/FyBH9nLaSPU/maxresdefault.jpg",
     "duration": "6 min", "description": "Calming techniques for exam-day nerves."},
    {"id": "r26", "category": "student", "type": "guide", "title": "The Burnout-Proof Study Plan",
     "source": "Velora Guide", "url": "https://www.headspace.com/articles/student-burnout",
     "image": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600",
     "duration": "8 min read", "description": "Spaced repetition + recovery for sustainable studying."},

    # SLEEP / EXTRA
    {"id": "r27", "category": "wellness", "type": "video", "title": "Sleep is Your Superpower — Matt Walker",
     "source": "TED", "url": "https://www.youtube.com/watch?v=5MuIMqhT8DM",
     "image": "https://img.youtube.com/vi/5MuIMqhT8DM/maxresdefault.jpg",
     "duration": "19 min", "description": "Why sleep matters more than you think — and how to get more."},
    {"id": "r28", "category": "anxiety", "type": "guide", "title": "Grounding 5-4-3-2-1 Technique",
     "source": "University of Rochester", "url": "https://www.urmc.rochester.edu/behavioral-health-partners/bhp-blog/april-2018/5-4-3-2-1-coping-technique-for-anxiety",
     "image": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=600",
     "duration": "2 min", "description": "A grounding tool for panic moments — name 5 sights, 4 sounds, 3 textures, 2 smells, 1 taste."},
    {"id": "r29", "category": "confidence", "type": "article", "title": "The Power of Self-Compassion",
     "source": "Greater Good (UC Berkeley)", "url": "https://greatergood.berkeley.edu/topic/self_compassion/definition",
     "image": "https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=600",
     "duration": "6 min read", "description": "How treating yourself like a friend changes everything."},
    {"id": "r30", "category": "productivity", "type": "guide", "title": "Atomic Habits — Cheat Sheet",
     "source": "James Clear", "url": "https://jamesclear.com/atomic-habits-summary",
     "image": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600",
     "duration": "10 min read", "description": "The four laws of behaviour change, in plain English."},
]

CATEGORIES = [
    {"key": "anxiety",       "title": "Anxiety Management",  "color": "from-purple-500/30 to-pink-500/30"},
    {"key": "stress",        "title": "Stress Relief",       "color": "from-blue-500/30 to-cyan-500/30"},
    {"key": "wellness",      "title": "Mental Wellness",     "color": "from-emerald-500/30 to-teal-500/30"},
    {"key": "confidence",    "title": "Self Confidence",     "color": "from-amber-500/30 to-orange-500/30"},
    {"key": "productivity",  "title": "Productivity",        "color": "from-indigo-500/30 to-purple-500/30"},
    {"key": "focus",         "title": "Focus Improvement",   "color": "from-cyan-500/30 to-blue-500/30"},
    {"key": "relationships", "title": "Relationships",       "color": "from-pink-500/30 to-rose-500/30"},
    {"key": "career",        "title": "Career Guidance",     "color": "from-violet-500/30 to-purple-500/30"},
    {"key": "student",       "title": "Student Wellness",    "color": "from-fuchsia-500/30 to-pink-500/30"},
]
